Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "hamidS" do |control|
    control.vm.hostname = "hamidS"
    control.vm.network "private_network", ip: "192.168.56.110"
    
    control.vm.provider "virtualbox" do |vb|
      vb.name = "hamidS"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
    
    control.vm.provision "shell", path: "scripts/install_k3s_apps.sh"
  end
end