BOX="ubuntu/jammy64"
BOX_URL="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-vagrant.box"

VM_MASTER_NAME="rsafS"
MASTER_IP="192.168.56.110"
CPU=1
MEM=1024

HOST_SRC_PATH=
VM_SRC_PATH=

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  config.vm.box_url = BOX_URL

  # this is Master Node.
  config.vm.define VM_MASTER_NAME do |control|
    control.vm.network "private_network", ip: MASTER_IP, name: "vboxnet0"
    control.vm.hostname = VM_MASTER_NAME
    control.vm.synced_folder ".", "/vagrant"
    control.vm.provision "shell" do |p|
      p.privileged = true
      p.path = "./scripts/install_k3s_apps.sh"
      p.args = [MASTER_IP, "Installing Master Node"]
    end
    control.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPU
      vb.name = VM_MASTER_NAME
      # Disable USB
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end
end